In [2]:
import pandas as pd
import numpy as np

In [6]:
public_futsal = pd.read_csv('data/Seoul_Public_Futsal_Field.csv')
public_futsal.head()

   연번           구장명                주소       비고         위도          경도
0   1       금천구 풋살장  서울 금천구 가산동 562-2  6:6, 야외  37.469092  126.882152
1   2    고척스카이돔풋살구장   서울 구로구 안양천로 545  6:6, 야외  37.495817  126.867397
2   3      난우중학교풋살장  서울 관악구 난곡로16길 32  6:6, 야외  37.466861  126.923310
3   4        오금풋살구장    서울 송파구 오금동 163  6:6, 야외  37.498468  127.138511
4   5  중랑천제5체육공원풋살장  서울 중랑구 중화동 345-2  6:6, 야외  37.605244  127.072198

In [3]:
private_futsal = pd.read_csv("data/Seoul_Private_Futsal_Field.csv")
len(private_futsal)

44

In [4]:
private_futsal.info

<bound method DataFrame.info of     연번                 구장명                                     주소       비고  \
0    1            스트리트풋살파크              서울 강서구 화곡로 142 메가스퀘어빌딩 8층  5:5, 옥상
1    2         로꼬풋살아레나신목동점                         서울 양천구 등촌로 100  4:4, 실내
2    3              한국풋살클럽                서울 양천구 등촌로 10 옥상 한국풋살클럽  4:4, 옥상
3    4              피치푸마목동            서울 양천구 목동서로 170 홈플러스 목동점 6F  6:6, 옥상
4    5          로꼬풋살아레나목동점                        서울 양천구 목동서로 213  4:4, 실내
5    6         로꼬풋살아레나신도림점            서울 구로구 신도림로11나길 8 지상, 지하 1층  4:4, 실내
6    7             킥오프풋볼클럽                    서울 영등포구 선유로 85 지하1층  4:4, 실내
7    8            업핏풋볼그라운드                     서울 영등포구 당산로 241 9F  4:4, 실내
8    9        플랩스타디움가산마리오점                      서울 금천구 벚꽃로 266 4층  5:5, 옥상
9   10              관악축구센터                    서울 관악구 관악로 116 지하1층  4:4, 실내
10  11                누리풋볼                    서울 강남구 논현로 748 지하1층  4:4, 실내
11  12           압구정풋살스튜디오                 서울 강남구 압구정로50길 28 지하1층  4:4, 실내
12  13         JMJ축구아카데미본점                서울 강남구 테헤란로19길 17 지하 1층  4:4, 실내
13  14            피엘풋볼아카데미                    서울 강남구 논현로86길 34 B2  4:4, 실내
14  15  로꼬풋살스타디움롯데마트제타플렉스점       서울 송파구 올림픽로 240 잠실롯데마트 제타플렉스동 R층  5:5, 옥상
15  16             강동송파풋살장                       서울 송파구 토성로 58 옥상  5:5, 옥상
16  17              천마풋살파크                      서울 송파구 성내천로29길 28  6:6, 야외
17  18           홍싸커&실내풋살장              서울 강동구 동남로 891 현대델리안 지하1층  4:4, 실내
18  19               고덕풋살장                  서울 강동구 아리수로 185 고덕풋살장  5:5, 야외
19  20               마루풋살장                 서울 도봉구 도당로 76 방학프라자 5층  4:4, 실내
20  21               루다풋살장               서울 도봉구 방학로 223 신동아프라자 옥상  6:6, 옥상
21  22               도봉풋살장                      서울 도봉구 방학로 266-50  6:6, 야외
22  23               라온풋살장                       서울 도봉구 방학동 553-2  6:6, 야외
23  24               하라풋살장                  서울 노원구 동일로 1323 하라프라자  6:6, 옥상
24  25       SMC풋살PARK이마트점                서울 노원구 마들로3길 37 상가 지하1층  4:4, 실내
25  26             티키타카스포츠            서울 강북구 솔샘로 243-9 2층 티키타카스포츠  4:4, 실내
26  27             서경대풋살파크                         서울 성북구 서경로 118  6:6, 야외
27  28            짐앤아이풋살센터                서울 노원구 공릉로 183 4층/5층 옥외  4:4, 실내
28  29       SMC풋살PARK광운대점                    서울 노원구 석계로 103 지하1층  4:4, 실내
29  30             성북실내풋살장                   서울 성북구 고려대로 29 지하 1층  4:4, 실내
30  31          HM풋살파크동대문점  서울 동대문구 천호대로 133 홈플러스 동대문점 옥상층 HM풋살파크  6:6, 옥상
31  32         로꼬풋살아레나동대문점                       서울 동대문구 답십리로 209  4:4, 실내
32  33              토모풋살파크                  서울 동대문구 천호대로69길 12 옥상  6:6, 옥상
33  34          성동FC성수동1가점                      서울 성동구 성수일로 57 3층  4:4, 옥상
34  35               성수풋살장                        서울 성동구 뚝섬로1길 18  4:4, 실내
35  36             성수실내축구장                         서울 성동구 성수이로 69  4:4, 실내
36  37      워커힐아파트상가옥상풋살파크                 서울 광진구 아차산로 635 워커힐아파트  5:5, 옥상
37  38     SKY SPORTS CLUB                  서울 광진구 구의로 28 5층 501호  5:5, 옥상
38  39               퍼스트사커                         서울 광진구 뚝섬로 548  4:4, 실내
39  40            비컴풋볼아카데미                     서울 성북구 보문로 70-1 b1  4:4, 실내
40  41          아디다스더베이스서울      서울 용산구 한강대로23길 55 현대아이파크몰 리빙파크 9층  6:6, 옥상
41  42        LIFE FC 축구교실                         서울 은평구 응암로 229  4:4, 실내
42  43           스카이필드 은평점    서울 은평구 통일로 1050 롯데몰 은평점 9층 스포테이먼트코어  6:6, 옥상
43  44             KTC실내풋살                  서울 구로구 고척로19길 41 매봉빌딩  4:4, 실내

   교육/대관         위도          경도
0     대관  37.540567  126.837582
1     대관  37.538855  126.863957
2     교육  37.530823  126.864236
3     대관  37.530244  126.873300
4     대관  37.528018  126.870616
5     대관  37.509084  126.879422
6     교육  37.521529  126.889530
7     교육  37.535215  126.902539
8     대관  37.478446  126.885081
9     교육  37.475604  126.953083
10    교육  37.518667  127.028943
11    교육  37.526647  127.037303
12    교육  37.501147  127.033182
13    교육  37.500357  127.040307
14    대관  37.510968  127.095369
15    교육  37.529030  127.116078
16    교육  37.502050  127.153526
17    교육  37.553315  127.155946
18    교육  37.561745  127.148711
19    교육  37.664572  127.035966
20    대관  37.661271  127.027471
21    대관  37.663201  127.022854
22    대관  37.660911  127.019472
23    대관  37.646809  127.062619
24    교육  37.628780  127.062012
25    교육  37.620195  127.019737
26    대관  37.613959  127.012925
27    교육  37.626113  127.079551
28    교육  37.622836  127.060711
29    교육  37.586557  127.022606
30    대관  37.574549  127.038768
31    대관  37.573000  127.064023
32    교육  37.568488  127.051889
33    교육  37.545717  127.049820
34    교육  37.542730  127.046720
35    교육  37.541370  127.055612
36    교육  37.549438  127.107217
37    교육  37.540293  127.089794
38    교육  37.534500  127.070709
39    교육  37.581774  127.021587
40    대관  37.529772  126.964741
41    교육  37.592409  126.917493
42    대관  37.637537  126.917900
43    교육  37.503006  126.844560  >

In [8]:
living = pd.read_csv('data/Seoul_Futsal_Living_Population.csv', encoding = 'cp949')
living.head()

        풋살인구  시간대            행정동명
0  1683.4231    0  서울특별시 강남구 개포1동
1  1694.0276    1  서울특별시 강남구 개포1동
2  1663.1650    2  서울특별시 강남구 개포1동
3  1690.3390    3  서울특별시 강남구 개포1동
4  1694.0927    4  서울특별시 강남구 개포1동

In [9]:
parking = pd.read_csv('data/Seoul_Public_Parking_Lot.csv',encoding='euc-kr')
parking.head()

               주차장명         위도          경도
0     초안산근린공원주차장(구)  37.649279  127.040474
1   마들스타디움(근린공원)(구)  37.643917  127.058567
2  마장동(건물) 공영주차장(구)  37.569939  127.035145
3       영등포여고 공영(구)  37.515205  126.915116
4      당산근린공원 공영(구)  37.525526  126.895794